### ISSUE TITLE
SSID with chinese characters are not listed

### ISSUE THREAD

**Issue by moontide** [raspberrypi-ui/lxplug-network#14]
With this plugin, SSID(s) with chinese characters are not listed. I have to install `network-manager-gnome` to connect SSID(s) with chinese characters.

**Comment by spl237** [comment]
The plugin is just the top end of a large stack of software, starting with dhcpcd and going further down from there - I've got no idea whereabouts in the stack this limitation occurs, but it is almost certainly below the plugin, so I really have no idea how to fix this issue. If you can submit a PR, I'm happy to take a look at it, but closing this in the absence of a PR.
