### ISSUE TITLE
Ignores PSK created with wpa_passphrase

### ISSUE THREAD

**Issue by Milliways2** [raspberrypi-ui/lxplug-network#4]
Ignores stored PSK created with wpa_passphrase and overwrites with passphrase in plain text.

**Comment by spl237** [comment]
I don't think that is anything to do with lxplug-network; all the passphrase behaviour is handled by dhcpcd and wpa_supplicant. Suggest you raise an issue with the author of dhcpcd on his repo - https://roy.marples.name/projects/dhcpcd

**Comment by Milliways2** [comment]
I looked at the code, and AKAIK it only looks for PSK in quotes.

**Comment by spl237** [comment]
The search for PSK in quotes is purely something the plugin does to save the user having to type it in again, as an indication that a PSK is already set for that network.

I've just tested this with wpa_passphrase data set in wpa_supplicant, and I see the following behaviour when connecting to an already-known network:

psk in quotes in wpa_supplicant - psk is read back into passphrase prompt; clicking ok reconnects to network. If text in passphrase prompt is all deleted, clicking ok still reconnects.

psk from wpa_passphrase (not in quotes) in wpa_supplicant - nothing read back into passphrase prompt; clicking ok reconnects to network.

psk from wpa_passphrase in wpa supplicant, along with psk in quotes with line #'ed at beginning - psk in quotes is read back into passphrase; clicking ok reconnects to network. But I think this is the situation where you are seeing problems, in that the wpa_passphrase psk is removed and replaced with the quoted passphrase.

This, as I said above, is a dhcpcd limitation - if text is provided at that prompt, it is assumed to be a passphrase, not a wpa_passphrase key. dhcpcd does not support the entry of wpa_passphrase data - which makes sense, as the wpa_passphrase string is not intended to be entered by the user anyway. Entering a wpa_passphrase string at the prompt results in a failure to connect.

The only thing I can think of to improve the above is to check to see if the psk= line in wpa_supplicant.conf has a hash at the start, and to not read it back into the prompt if so. That should deal with the overwriting issue you mention, but it does then mean there is no indication that this is a network to which you have already connected and that no PSK is needed.

**Comment by Milliways2** [comment]
Simon,

Agreed - if you don't enter a PSK it does connect.
This is just not obvious.
