### ISSUE TITLE
Icon for 5GHz networks is wonky

### ISSUE THREAD

**Issue by andrum99** [raspberrypi-ui/lxplug-network#8]
The included icons for 5GHz networks seem to be ignored. These are a white 5 in a red circle at 16x16 and 24x24 resolutions. On Raspbian, the applet currently displays an icon that says 5G in red text - see attached screenshot:
![desktop-5g-icon](https://user-images.githubusercontent.com/58046090/81989400-118b5b00-9635-11ea-9c50-22332578cbf5.png)

5G could be seen as referring to 5G mobile rather than the 5GHz wireless LAN band. Better to use the included 5 icon to avoid any potential confusion. (I've had a similar fixup to a page in the main documentation repo accepted recently - see https://github.com/raspberrypi/documentation/pull/1498).

**Comment by spl237** [comment]
You're quite right - the "5G" icons have been appearing for so long that I'd completely forgotten we had the custom icons of our own. I wonder how and when that happened!

I'll have a dig about and see if I can find what changed - it may be that we deliberately changed them for the 5G ones in a theme update, but I'll check.

**Comment by spl237** [comment]
Ah - yes, we did decide to change them when we updated the icon theme a few months later. The 5G icons come from the rpd icon theme, so the change was deliberate. We felt the meaning of the "5" on its own wasn't particularly clear, and that adding the "G" made it more obvious.

**Comment by andrum99** [comment]
> Ah - yes, we did decide to change them when we updated the icon theme a few months later. The 5G icons come from the rpd icon theme, so the change was deliberate. We felt the meaning of the "5" on its own wasn't particularly clear, and that adding the "G" made it more obvious.

Hmmm, OK.
